--- #remove plabook
- hosts: all
  user: ansible
  connection: ssh
  become: yes
  gather_facts: yes

  tasks:
    - name: remove-httpd
      action: yum pkg=httpd state=absent

    - name: remove-tree
      action: yum pkg=tree state=absent
  
    - name: remove-git
      action: yum pkg=git state=absent
